### ISSUE TITLE
Plug-in just installed but no settings panel

### ISSUE THREAD

**Issue by pelted** [frenchie4111/complicated-octoprint#4]
Just installed the plugin just fine with the latest OctoPrint (1.3.11), but no settings screen for it is showing up in the plugin list. Plugin Manager shows installed and active but no way of accessing the settings.

**Comment by KasimAhmic** [comment]
If you click the settings icon in the top right hand corner of the main OctoPrint page, the settings for Complicated are located at the very bottom of the left hand navigation menu under the name “Complicated Apple Watch.”

You probably have found it already so I’m just answering for the sake of completeness as well as if anyone else has the same question.

**Comment by frenchie4111** [comment]
The app requires an octoprint reset after install, then it should appear in settings.
